// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUf-LSvQLsxBp7hsWEm2OXOG2G8xIjzXk',
    appId: '1:543181031833:ios:70f55a8770af77662b6b08',
    messagingSenderId: '543181031833',
    projectId: 'healthease-c8480',
    storageBucket: 'healthease-c8480.appspot.com',
    iosBundleId: 'com.example.healthEaze',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMaPm3TtsHiUn0AwLZtqywSR68_mAwRPs',
    appId: '1:543181031833:web:abb7e005453e30a02b6b08',
    messagingSenderId: '543181031833',
    projectId: 'healthease-c8480',
    authDomain: 'healthease-c8480.firebaseapp.com',
    storageBucket: 'healthease-c8480.appspot.com',
    measurementId: 'G-9QDB4VG6G3',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMaPm3TtsHiUn0AwLZtqywSR68_mAwRPs',
    appId: '1:543181031833:web:abb7e005453e30a02b6b08',
    messagingSenderId: '543181031833',
    projectId: 'healthease-c8480',
    authDomain: 'healthease-c8480.firebaseapp.com',
    storageBucket: 'healthease-c8480.appspot.com',
    measurementId: 'G-9QDB4VG6G3',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUf-LSvQLsxBp7hsWEm2OXOG2G8xIjzXk',
    appId: '1:543181031833:ios:70f55a8770af77662b6b08',
    messagingSenderId: '543181031833',
    projectId: 'healthease-c8480',
    storageBucket: 'healthease-c8480.appspot.com',
    iosBundleId: 'com.example.healthEaze',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ800Woa1hPvQRfKKUi99-VgfsHWM5Xc0',
    appId: '1:543181031833:android:7c298ac858a2fbda2b6b08',
    messagingSenderId: '543181031833',
    projectId: 'healthease-c8480',
    storageBucket: 'healthease-c8480.appspot.com',
  );

}