// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe8FP0uby1LMcT5E4ObpdYrOzY6PoZ8vo',
    appId: '1:915505110368:web:3e9718ce1e5427ebafd205',
    messagingSenderId: '915505110368',
    projectId: 'health-ease-ae456',
    authDomain: 'health-ease-ae456.firebaseapp.com',
    storageBucket: 'health-ease-ae456.appspot.com',
    measurementId: 'G-HKJFNT44Z0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe9dZCGmMv3M2DckiXEhGcO3HhQxtkUIA',
    appId: '1:915505110368:android:d8f9fab1c998d613afd205',
    messagingSenderId: '915505110368',
    projectId: 'health-ease-ae456',
    storageBucket: 'health-ease-ae456.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2nXYDDV07pTrPTZNdDbxxGjdOwSeEGMA',
    appId: '1:915505110368:ios:be37dc440b8ad074afd205',
    messagingSenderId: '915505110368',
    projectId: 'health-ease-ae456',
    storageBucket: 'health-ease-ae456.appspot.com',
    iosBundleId: 'com.example.healthEaze',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2nXYDDV07pTrPTZNdDbxxGjdOwSeEGMA',
    appId: '1:915505110368:ios:be37dc440b8ad074afd205',
    messagingSenderId: '915505110368',
    projectId: 'health-ease-ae456',
    storageBucket: 'health-ease-ae456.appspot.com',
    iosBundleId: 'com.example.healthEaze',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe8FP0uby1LMcT5E4ObpdYrOzY6PoZ8vo',
    appId: '1:915505110368:web:5b3fad0541fcdafdafd205',
    messagingSenderId: '915505110368',
    projectId: 'health-ease-ae456',
    authDomain: 'health-ease-ae456.firebaseapp.com',
    storageBucket: 'health-ease-ae456.appspot.com',
    measurementId: 'G-K64J56WPJ1',
  );
}
